apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  name: sparkoperator-prometheusrules
  namespace: {{.Namespace}}
spec:
  groups:
      - name: SLOs-probe_success_spark_operator
        rules:
          - alert: Spark Operator Probe Success Burn Rate
            annotations:
              message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
              summary: Spark Operator Probe Success Burn Rate
            expr: |
              sum(probe_success:burnrate5m{instance=~"spark-operator-controller-manager"}) by (instance) > (14.40 * (1-0.98000))
              and
              sum(probe_success:burnrate1h{instance=~"spark-operator-controller-manager"}) by (instance) > (14.40 * (1-0.98000))
            for: 2m
            labels:
              severity: warning
              instance: spark-operator-controller-manager
    
          - alert: Spark Operator Probe Success Burn Rate
            annotations:
              message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
              summary: Spark Operator Probe Success Burn Rate
            expr: |
              sum(probe_success:burnrate30m{instance=~"spark-operator-controller-manager"}) by (instance) > (6.00 * (1-0.98000))
              and
              sum(probe_success:burnrate6h{instance=~"spark-operator-controller-manager"}) by (instance) > (6.00 * (1-0.98000))
            for: 15m
            labels:
              severity: warning
              instance: spark-operator-controller-manager
    
          - alert: Spark Operator Probe Success Burn Rate
            annotations:
              message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
              summary: Spark Operator Probe Success Burn Rate
            expr: |
              sum(probe_success:burnrate2h{instance=~"spark-operator-controller-manager"}) by (instance) > (3.00 * (1-0.98000))
              and
              sum(probe_success:burnrate1d{instance=~"spark-operator-controller-manager"}) by (instance) > (3.00 * (1-0.98000))
            for: 1h
            labels:
              severity: warning
              instance: spark-operator-controller-manager
      
      # RecordingRules for Spark Operator 
      - name: SLOs - Spark Operator
        rules:
        - expr: |
            absent(up{job="spark-operator"}) * 0 or vector(1)
          labels:
            instance: spark-operator-controller-manager
          record: probe_success
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[1d]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate1d
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[1h]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate1h
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[2h]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate2h
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[30m]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate30m
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[3d]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate3d
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[5m]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate5m
    
        - expr: |
            1 - min(avg_over_time(probe_success{instance="spark-operator-controller-manager"}[6h]))
          labels:
            instance: spark-operator-controller-manager
          record: probe_success:burnrate6h
