---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: data-science-prometheus-instance-ingress
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: data-science-monitoringstack
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: data-science-prometheus-namespace-proxy
        - podSelector:
            matchLabels:
              app: data-science-prometheus-cluster-proxy
      ports:
        - protocol: TCP
          port: 9090
