# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/base
resources:
- bases/mlflow.opendatahub.io_mlflows.yaml
# +kubebuilder:scaffold:crdkustomizeresource
