apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-science-admingroup-ingress-role
  namespace: openshift-ingress
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - tokenratelimitpolicies
  resourceNames:
  - gateway-token-rate-limits
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - kuadrant.io
  resources:
  - ratelimitpolicies
  resourceNames:
  - gateway-rate-limits
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
