apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds odh namespace to all resources.
namespace: opendatahub

patches:
# patch to remove default `system` namespace in ../../manager/manager.yaml
- path: patches/delete-namespace.yaml

# patch to add OpenShift serving cert annotation in metrics service
- path: patches/auth_proxy_service_patch.yaml

# patch to add serving cert to auth proxy container
- path: patches/manager_auth_proxy_patch.yaml

# patch to add istio config properties
- path: patches/manager_istio_config_patch.yaml

# patch to add webhooks and CA bundles to CRD
- path: patches/webhook_in_modelregistries.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# patch to add webhooks to manager
- path: patches/manager_webhook_patch.yaml

# patch to add storage migration environment variables
- path: patches/manager_migration_env_patch.yaml

# patch to add CA bundles in Webhooks
- path: patches/mutatingwh_cainjection_patch.yaml
- path: patches/validatingwh_cainjection_patch.yaml

# patch to add OpenShift serving cert to webhook-service
- path: patches/webhook_service_patch.yaml

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    component.opendatahub.io/name: model-registry-operator
    opendatahub.io/component: "true"
    control-plane: model-registry-operator

# Overlay on operator default config with prometheus monitor
resources:
- ../../default
- ../../jobs-async-upload
- ../../webhook

# Config map and replacements to use params.env for use in opendatahub-operator
configMapGenerator:
- envs:
    - params.env
  name: model-registry-operator-parameters
generatorOptions:
  disableNameSuffixHash: true
replacements:
- path: replacements.yaml
