---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-datasciencecluster
  failurePolicy: Fail
  name: datasciencecluster-defaulter.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datascienceclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-datasciencecluster
  failurePolicy: Fail
  name: datasciencecluster-validator.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - datascienceclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dscinitialization
  failurePolicy: Fail
  name: dscinitialization-validator.opendatahub.io
  rules:
  - apiGroups:
    - dscinitialization.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - DELETE
    resources:
    - dscinitializations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kueue
  failurePolicy: Fail
  name: kserve-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kueue
  failurePolicy: Fail
  name: kubeflow-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pytorchjobs
    - notebooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kueue
  failurePolicy: Fail
  name: ray-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - ray.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rayjobs
    - rayclusters
  sideEffects: None
