apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: opendatahub-operator-controller-webhook-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: opendatahub-operator
    control-plane: controller-manager
