apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: redhat-ods-operator

resources:
- ../crd
- ../rbac
- ../manager
- ../webhook

patches:
- path: manager_auth_proxy_patch.yaml
- path: manager_webhook_patch.yaml
