apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-operator
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: rhods-operator
          env:
          - name: OPERATOR_VERSION
            value: "REPLACE_OPERATOR_VERSION"
