apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: rhods
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
spec:
  components:
    codeflare:
      managementState: "Removed"
    dashboard:
      managementState: "Managed"
    datasciencepipelines:
      managementState: "Managed"
    kserve: {
      managementState: "Managed",
      serving: {
        ingressGateway: {
          certificate: {
            type: SelfSigned
          }
        },
        name: "knative-serving",
        managementState: "Managed"
      }
    }
    modelmeshserving:
      managementState: "Managed"
    kueue:
      managementState: "Removed"
    ray:
      managementState: "Removed"
    workbenches:
      managementState: "Managed"
