apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opendatahub-operator
spec:
  components:
    codeflare:
      managementState: "Managed"
    dashboard:
      managementState: "Managed"
    datasciencepipelines:
      managementState: "Managed"
    kserve: {
      managementState: "Managed",
      serving: {
        ingressGateway: {
          certificate: {
            type: OpenshiftDefaultIngress
          }
        },
        name: "knative-serving",
        managementState: "Managed"
      }
    }
    modelmeshserving:
      managementState: "Managed"
    kueue:
      managementState: "Managed"
    trainingoperator:
      managementState: "Removed"
    ray:
      managementState: "Managed"
    workbenches:
      managementState: "Managed"
    trustyai:
      managementState: "Managed"
    modelregistry:
      managementState: "Removed"
