apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  labels:
    app.kubernetes.io/name: dscinitialization
    app.kubernetes.io/instance: rhods-setup
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
  name: default-dsci
spec:
  monitoring:
    managementState: "Managed"
    namespace: 'redhat-ods-monitoring'
  applicationsNamespace: 'redhat-ods-applications'

