apiVersion: dscinitialization.opendatahub.io/v1alpha1
kind: DSCInitialization
metadata:
  labels:
    app.kubernetes.io/name: dscinitialization
    app.kubernetes.io/instance: dscinitialization-sample
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opendatahub-operator
  name: dscinitialization-sample
spec:
  monitoring:
    enabled: false
    namespace: 'opendatahub'
  applicationsNamespace:
    - opendatahub