apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  labels:
    app.kubernetes.io/name: dscinitialization
    app.kubernetes.io/instance: default-dsci
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opendatahub-operator
  name: default-dsci
spec:
  monitoring:
    managementState: "Managed"
    namespace: 'opendatahub'
    metrics: {}
  applicationsNamespace: 'opendatahub'
  serviceMesh:
    controlPlane:
      metricsCollection: Istio
      name: data-science-smcp
      namespace: istio-system
    managementState: "Managed"
  trustedCABundle:
    managementState: "Managed"
    customCABundle: ""

