## Append samples you want in your CSV to this file as resources ##
resources:
- dscinitialization_v1alpha1_dscinitialization.yaml
- datasciencecluster_v1alpha1_datasciencecluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
