apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - torch_distributed_rocm.yaml
  - torch_distributed_th03_cuda128_torch28_py312.yaml
  - torch_distributed.yaml
  - training_hub_th03_cuda128_torch28_py312.yaml
  - training_hub.yaml
