apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-template-amd-rocm
  annotations:
    openshift.io/display-name: vLLM AMD GPU LLMInferenceServiceConfig
    description: vLLM AMD GPU LLMInferenceServiceConfig for LLMInferenceService.
spec:
  template:
    containers:
      - name: main
        image: $(kserve-vllm-rocm)
