apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: CoreWeaveKubernetesEngine
metadata:
  name: opendatahub-coreweave-kubernetes-engine
spec:
  dependencies:
    certManager:
      managementPolicy: Managed
    lws:
      managementPolicy: Managed
    sailOperator:
      managementPolicy: Managed
