apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opendatahub-coreweave-cloud-manager-leader-election-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opendatahub-coreweave-cloud-manager-leader-election-role
subjects:
- kind: ServiceAccount
  name: opendatahub-coreweave-cloud-manager-operator
  namespace: system
