apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  name: modelmeshserving-prometheusrules
  namespace: {{.Namespace}}
spec:
  groups:
      - name: SLOs-probe_success_modelmesh
        rules:
        - alert: Modelmesh Controller Probe Success Burn Rate
          annotations:
            message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
            summary: Modelmesh Controller Probe Success Burn Rate
          expr: |
            sum(probe_success:burnrate5m{instance=~"modelmesh-controller"}) by (instance) > (14.40 * (1-0.98000))
            and
            sum(probe_success:burnrate1h{instance=~"modelmesh-controller"}) by (instance) > (14.40 * (1-0.98000))
          for: 2m
          labels:
            severity: critical
            namespace: redhat-ods-applications
        - alert: Modelmesh Controller Probe Success Burn Rate
          annotations:
            message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
            summary: Modelmesh Controller Probe Success Burn Rate
          expr: |
            sum(probe_success:burnrate30m{instance=~"modelmesh-controller"}) by (instance) > (6.00 * (1-0.98000))
            and
            sum(probe_success:burnrate6h{instance=~"modelmesh-controller"}) by (instance) > (6.00 * (1-0.98000))
          for: 15m
          labels:
            severity: critical
            namespace: redhat-ods-applications
        - alert: Modelmesh Controller Probe Success Burn Rate
          annotations:
            message: 'High error budget burn for {{`{{`}}$labels.instance{{`}}`}} (current value: {{`{{`}}$value{{`}}`}} ).'
            summary: Modelmesh Controller Probe Success Burn Rate
          expr: |
            sum(probe_success:burnrate2h{instance=~"modelmesh-controller"}) by (instance) > (3.00 * (1-0.98000))
            and
            sum(probe_success:burnrate1d{instance=~"modelmesh-controller"}) by (instance) > (3.00 * (1-0.98000))
          for: 1h
          labels:
            severity: warning
            namespace: redhat-ods-applications

      # RecordingRules for Modelmesh Controller
      - name: SLOs - Modelmesh Controller
        rules:
        - expr: |
            absent(up{job=~'Modelmesh Controller'}) * 0 or vector(1)
          labels:
            instance: modelmesh-controller
          record: probe_success
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[1d]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate1d
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[1h]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate1h
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[2h]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate2h
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[30m]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate30m
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[3d]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate3d
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[5m]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate5m
        - expr: |
            1 - min(avg_over_time(probe_success{instance="modelmesh-controller"}[6h]))
          labels:
            instance: modelmesh-controller
          record: probe_success:burnrate6h
