apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  annotations:
    opendatahub.io/dashboard-feature-visibility: '[]'
    opendatahub.io/description: 'This profile offers 2 CPUs and 4 GiB of memory. You can customize these resources up to 4 CPUs and 8 GiB of memory.'
    opendatahub.io/disabled: 'false'
    opendatahub.io/display-name: default-profile
    opendatahub.io/managed: "false"
  name: default-profile
  namespace: opendatahub
spec:
  identifiers:
    - defaultCount: 2
      displayName: CPU
      identifier: cpu
      maxCount: 4
      minCount: 1
      resourceType: CPU
    - defaultCount: 4Gi
      displayName: Memory
      identifier: memory
      maxCount: 8Gi
      minCount: 2Gi
      resourceType: Memory
