apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-openshift-overlay

resources:
  - ../../base/networking/maas
  - ../odh
  - ../../base/policies/usage-policies
  - ../../base/observability