apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: replace-description-patch
spec:
  description: |-
    Red Hat OpenShift Data Science (RHODS) is a machine-learning-as-a-service
    platform built on Red Hat's Kubernetes-based OpenShift Container Platform,
    Ceph Object Storage, and integrating a collection of open source projects.

    The RHODS operator allows users to install and manage RHODS components.
    Users can mix and match tools from each project to fulfill the needs of
    their use case. Each of the projects share some components, but can be
    mostly seen as an extension of each other to provide as complete a solution
    as possible for enterprise users.
    
    ### Components
    
    * Open Data Hub Dashboard - A web dashboard that displays installed Open Data Hub components with easy access to component UIs and documentation
    * ODH Notebook Controller - Secure management of Jupyter Notebook in Kubernetes environments built on top of Kubeflow Notebook Controller with support for OAuth
    * Jupyter Notebooks - JupyterLab notebook that provide Python support for GPU workloads
    * Data Science Pipelines - Pipeline solution for end to end MLOps workflows that support the Kubeflow Pipelines SDK and Tekton
    * Model Mesh - ModelMesh Serving is the Controller for managing ModelMesh, a general-purpose model serving management/routing layer
    * Distributed Workloads(Incubation) - Stack built to make managing distributed compute infrastructure in the cloud easy and intuitive for Data Scientists. This stack consists of two components 
                                          Codeflare and KubeRay.
    * Kserve (Incubation) - Kserve is the Controller for for serving machine learning (ML) models on arbitrary frameworks
