---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: datascienceclusters.datasciencecluster.opendatahub.io
spec:
  group: datasciencecluster.opendatahub.io
  names:
    kind: DataScienceCluster
    listKind: DataScienceClusterList
    plural: datascienceclusters
    singular: datasciencecluster
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DataScienceCluster is the Schema for the datascienceclusters
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DataScienceClusterSpec defines the desired state of DataScienceCluster
            properties:
              components:
                description: Components are used to override and fine tune specific
                  component configurations.
                properties:
                  dashboard:
                    description: Dashboard component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                    type: object
                  serving:
                    description: Serving component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                      testConfigMap:
                        description: ConfigMap holds configuration data for pods to
                          consume.
                        properties:
                          apiVersion:
                            description: 'APIVersion defines the versioned schema
                              of this representation of an object. Servers should
                              convert recognized schemas to the latest internal value,
                              and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                            type: string
                          binaryData:
                            additionalProperties:
                              format: byte
                              type: string
                            description: BinaryData contains the binary data. Each
                              key must consist of alphanumeric characters, '-', '_'
                              or '.'. BinaryData can contain byte sequences that are
                              not in the UTF-8 range. The keys stored in BinaryData
                              must not overlap with the ones in the Data field, this
                              is enforced during validation process. Using this field
                              will require 1.10+ apiserver and kubelet.
                            type: object
                          data:
                            additionalProperties:
                              type: string
                            description: Data contains the configuration data. Each
                              key must consist of alphanumeric characters, '-', '_'
                              or '.'. Values with non-UTF-8 byte sequences must use
                              the BinaryData field. The keys stored in Data must not
                              overlap with the keys in the BinaryData field, this
                              is enforced during validation process.
                            type: object
                          immutable:
                            description: Immutable, if set to true, ensures that data
                              stored in the ConfigMap cannot be updated (only object
                              metadata can be modified). If not set to true, the field
                              can be modified at any time. Defaulted to nil.
                            type: boolean
                          kind:
                            description: 'Kind is a string value representing the
                              REST resource this object represents. Servers may infer
                              this from the endpoint the client submits requests to.
                              Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                            type: string
                          metadata:
                            description: 'Standard object''s metadata. More info:
                              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
                            type: object
                        type: object
                    type: object
                  training:
                    description: DataServicePipeline component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                    type: object
                  workbenches:
                    description: Workbenches component configuration
                    properties:
                      enabled:
                        description: enables or disables the component. A disabled
                          component will not be installed.
                        type: boolean
                      managedImages:
                        description: List of configurable controllers/deployments
                        type: boolean
                    type: object
                type: object
              manifestsUri:
                description: URI to the manifests repository. If not defined, defaults
                  to the embedded manifests
                type: string
              profile:
                description: 'A profile sets the default components and configuration
                  to install for a given use case. The profile configuration can still
                  be overriden by the user on a per component basis. If not defined,
                  the ''full'' profile is used. Valid values are: - full: all components
                  are installed - serving: only serving components are installed -
                  training: only training components are installed - workbench: only
                  workbench components are installed'
                type: string
            type: object
          status:
            description: DataScienceClusterStatus defines the observed state of DataScienceCluster
            properties:
              conditions:
                description: Conditions describes the state of the DataScienceCluster
                  resource.
                items:
                  description: Condition represents the state of the operator's reconciliation
                    functionality.
                  properties:
                    lastHeartbeatTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      description: ConditionType is the state of the operator's reconciliation
                        functionality.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              errorMessage:
                type: string
              phase:
                description: Phase describes the Phase of DataScienceCluster reconciliation
                  state This is used by OLM UI to provide status information to the
                  user
                type: string
              relatedObjects:
                description: RelatedObjects is a list of objects created and maintained
                  by this operator. Object references will be added to this list after
                  they have been created AND found in the cluster.
                items:
                  description: "ObjectReference contains enough information to let
                    you inspect or modify the referred object. --- New uses of this
                    type are discouraged because of difficulty describing its usage
                    when embedded in APIs. 1. Ignored fields.  It includes many fields
                    which are not generally honored.  For instance, ResourceVersion
                    and FieldPath are both very rarely valid in actual usage. 2. Invalid
                    usage help.  It is impossible to add specific help for individual
                    usage.  In most embedded usages, there are particular restrictions
                    like, \"must refer only to types A and B\" or \"UID not honored\"
                    or \"name must be restricted\". Those cannot be well described
                    when embedded. 3. Inconsistent validation.  Because the usages
                    are different, the validation rules are different by usage, which
                    makes it hard for users to predict what will happen. 4. The fields
                    are both imprecise and overly precise.  Kind is not a precise
                    mapping to a URL. This can produce ambiguity during interpretation
                    and require a REST mapping.  In most cases, the dependency is
                    on the group,resource tuple and the version of the actual struct
                    is irrelevant. 5. We cannot easily change it.  Because this type
                    is embedded in many locations, updates to this type will affect
                    numerous schemas.  Don't make new APIs embed an underspecified
                    API type they do not control. \n Instead of using this type, create
                    a locally provided and used type that is well-focused on your
                    reference. For example, ServiceReferences for admission registration:
                    https://github.com/kubernetes/api/blob/release-1.17/admissionregistration/v1/types.go#L533
                    ."
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    fieldPath:
                      description: 'If referring to a piece of an object instead of
                        an entire object, this string should contain a valid JSON/Go
                        field access statement, such as desiredState.manifest.containers[2].
                        For example, if the object reference is to a container within
                        a pod, this would take on a value like: "spec.containers{name}"
                        (where "name" refers to the name of the container that triggered
                        the event) or if no container name is specified "spec.containers[2]"
                        (container with index 2 in this pod). This syntax is chosen
                        only to have some well-defined way of referencing a part of
                        an object. TODO: this design is not final and this field is
                        subject to change in the future.'
                      type: string
                    kind:
                      description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                    namespace:
                      description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                      type: string
                    resourceVersion:
                      description: 'Specific resourceVersion to which this reference
                        is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                      type: string
                    uid:
                      description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
