---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: kfconfigs.kfconfig.apps.kubeflow.org.my.domain
spec:
  group: kfconfig.apps.kubeflow.org.my.domain
  names:
    kind: KfConfig
    listKind: KfConfigList
    plural: kfconfigs
    singular: kfconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KfConfig is the Schema for the kfconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KfConfigSpec defines the desired state of KfConfig
            properties:
              appDir:
                description: 'Shared fields among all components. should limit this
                  list. TODO(gabrielwen): Deprecate AppDir and move it to cache in
                  Status.'
                type: string
              applications:
                items:
                  description: Application defines an application to install
                  properties:
                    kustomizeConfig:
                      properties:
                        overlays:
                          items:
                            type: string
                          type: array
                        parameters:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        repoRef:
                          properties:
                            name:
                              type: string
                            path:
                              type: string
                          type: object
                      type: object
                    name:
                      type: string
                  type: object
                type: array
              configFileName:
                description: The filename of the config, e.g. app.yaml. Base name
                  only, as the directory is AppDir above.
                type: string
              deleteStorage:
                type: boolean
              email:
                type: string
              hostname:
                type: string
              ipName:
                type: string
              platform:
                type: string
              plugins:
                items:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    spec:
                      type: object
                  type: object
                type: array
              project:
                description: 'TODO(gabrielwen): Deprecate these fields as they only
                  makes sense to GCP.'
                type: string
              repos:
                items:
                  description: Repo provides information about a repository providing
                    config (e.g. kustomize packages, Deployment manager configs, etc...)
                  properties:
                    name:
                      description: Name is a name to identify the repository.
                      type: string
                    uri:
                      description: 'URI where repository can be obtained. Can use
                        any URI understood by go-getter: https://github.com/hashicorp/go-getter/blob/master/README.md#installation-and-usage'
                      type: string
                  type: object
                type: array
              secrets:
                items:
                  description: Secret provides information about secrets needed to
                    configure Kubeflow. Secrets can be provided via references.
                  properties:
                    name:
                      type: string
                    secretSource:
                      properties:
                        envSource:
                          properties:
                            name:
                              type: string
                          type: object
                        hashedSource:
                          properties:
                            value:
                              type: string
                          type: object
                        literalSource:
                          properties:
                            value:
                              type: string
                          type: object
                      type: object
                  type: object
                type: array
              skipInitProject:
                type: boolean
              useBasicAuth:
                description: 'TODO(gabrielwen): Can we infer this from Applications?'
                type: boolean
              version:
                type: string
              zone:
                type: string
            type: object
          status:
            properties:
              caches:
                items:
                  properties:
                    localPath:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                    type:
                      description: Type of deployment condition.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
