name: Build and push catalog image for main branch

on:
  push:
    branches:
      - main

permissions: {}

env:
  IMAGE_TAG_BASE: quay.io/${{ secrets.QUAY_ORG }}/opendatahub-operator

jobs:
  create-catalog-image:
    name: Build/push catalog image
    runs-on: ubuntu-latest
    env:
      IMAGE_BUILDER: podman
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Quay.io login
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Create bundle image
        env:
          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:latest
          IMG_TAG: latest
          VERSION: latest
        run: |
          make bundle-build
          make bundle-push

      - name: Build and push catalog image
        env:
          CATALOG_IMG: ${{ env.IMAGE_TAG_BASE }}-catalog:latest
          BUNDLE_IMG: ${{ env.IMAGE_TAG_BASE }}-bundle:latest
        run: |
          make catalog-build
          make catalog-push
