name: Get merge commit

on:
  workflow_call:
    outputs:
      mergedSha:
        description: "The merge commit SHA"
        value: ${{ jobs.resolve-merge-commit.outputs.mergedSha }}

permissions: { }

jobs:
  resolve-merge-commit:
    runs-on: ubuntu-24.04
    outputs:
      mergedSha: ${{ steps.merged.outputs.mergedSha }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          path: base
          sparse-checkout: .github/scripts

      - name: Check if the PR can be merged and get the test merge commit
        id: merged
        env:
          GH_TOKEN: ${{ github.token }}
          GH_EVENT: ${{ github.event_name }}
        run: |
          chmod +x base/.github/scripts/get-merge-commit.sh
          case "$GH_EVENT" in
            pull_request_target)
              if mergedSha=$(base/.github/scripts/get-merge-commit.sh ${{ github.repository }} ${{ github.event.number }}); then
                echo "Checking the merge commit $mergedSha"
                echo "mergedSha=$mergedSha" >> "$GITHUB_OUTPUT"
              else
                # Skipping so that no notifications are sent
                echo "Skipping the rest..."
              fi
              ;;
          esac
          rm -rf base
