name: Run prometheus unit tests
on:
  pull_request:
    paths:
      - 'internal/controller/components/**/monitoring/*-prometheusrules.tmpl.yaml'
      - 'internal/controller/components/**/monitoring/*-alerting.unit-tests.yaml'
      - 'tests/prometheus_unit_tests/scripts/**'
      - 'Makefile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
    - name: Install Promtool
      run: |
        sudo apt-get update && sudo apt-get install -y prometheus
    - name: Run prometheus-unit-tests
      run : make test-alerts
