name: Test Github Secrets
on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
      - "incubation"
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'

env:
  QUAY_ORG: ${{ secrets.QUAY_ORG}}
  IMAGE_REGISTRY: quay.io
  IMAGE_NAME: opendatahub-operator
  IMAGE_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
    - name: Log to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_TOKEN }}
        registry: ${{ env.IMAGE_REGISTRY}}

    - name: Pull image
      run: | 
          # Pull the image from registry
          while true
          do
            echo "Pulling image from Quay.io";
            sleep 10
            if podman pull quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            then
              break
            fi
          done
