name: Run prometheus unit tests
on:
  pull_request:
    paths:
      - 'internal/controller/components/**/monitoring/*-prometheusrules.tmpl.yaml'
      - 'internal/controller/components/**/monitoring/*-alerting.unit-tests.yaml'
      - 'tests/prometheus_unit_tests/scripts/**'
      - 'Makefile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Install Promtool
      run: |
        sudo apt-get update && sudo apt-get install -y prometheus
    - name: Run prometheus-unit-tests
      run : make test-alerts
