# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/rhods-operator.clusterserviceversion.yaml
- ../default
- ../../prometheus
- ../samples # to generate CSV alm-example
- ../../scorecard

patches:
- path: description-patch.yml
  target:
    group: operators.coreos.com
    kind: ClusterServiceVersion
# Remove inject-cabundle annotation from specific CRDs for OLM bundle
- patch: |-
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1inject-cabundle
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: dscinitializations.dscinitialization.opendatahub.io
- patch: |-
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1inject-cabundle
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: datascienceclusters.datasciencecluster.opendatahub.io

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
#patches:
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: controller-manager
#    namespace: system
#  patch: |-
#    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
#    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
#    - op: remove
#      path: /spec/template/spec/containers/1/volumeMounts/0
#    # Remove the "cert" volume, since OLM will create and mount a set of certs.
#    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
#    - op: remove
#      path: /spec/template/spec/volumes/0
